
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lilil
 */
public class Caça_Níqueis extends javax.swing.JFrame {
int Pikachus = 20;
    /**
     * Creates new form Caça_Níqueis
     */
    public Caça_Níqueis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jogar = new javax.swing.JButton();
        lbPikachus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Caça Níqueis");

        lb1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lb1.setText("5");

        lb2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lb2.setText("7");

        lb3.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lb3.setText("9");

        jogar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jogar.setText("Jogar");
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });

        lbPikachus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPikachus.setText("Pikachus 20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(lbPikachus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(lb2)
                        .addGap(89, 89, 89)
                        .addComponent(lb3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jogar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPikachus)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1)
                    .addComponent(lb2)
                    .addComponent(lb3))
                .addGap(38, 38, 38)
                .addComponent(jogar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        Pikachus -= 1;
        
        int slot1 = (int)(Math.random()*9+1);
        int slot2 = (int)(Math.random()*9+1);
        int slot3 = (int)(Math.random()*9+1);
        lb1.setText(String.valueOf(slot1));
        lb2.setText(String.valueOf(slot2));
        lb3.setText(String.valueOf(slot3));
        
        
        if (slot1 == slot2 && slot2 == slot3){
            switch (slot1){
                case 5:
                    Pikachus += 20 + 1;
                    JOptionPane.showMessageDialog(this, "Ganhasse 20 Pikachus");
                    break;
                case 7:
                    Pikachus += 50 + 1;
                    JOptionPane.showMessageDialog(this, "Ganhasse 50 Pikachus");
                    break;
                case 9:
                    Pikachus += 20 + 1;
                    JOptionPane.showMessageDialog(this, "Ganhasse 20 Pikachus");
                    break;
                default:
                    Pikachus += slot1 + 1;
                    JOptionPane.showMessageDialog(this, "Ganhasse" + slot1+ "Pikachus");
                    break;
            }
        }
        lbPikachus.setText("Pikachus" + String.valueOf(Pikachus));
        if(Pikachus == 0){
            int numero = JOptionPane.showConfirmDialog(this, "Jogar denovo","Maquina traga Pikachus",JOptionPane.YES_NO_OPTION);
            if(numero == 0){
                Pikachus = 20;
                lbPikachus.setText("Pikachus" + String.valueOf(Pikachus));
            }else{
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caça_Níqueis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caça_Níqueis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caça_Níqueis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caça_Níqueis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caça_Níqueis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jogar;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbPikachus;
    // End of variables declaration//GEN-END:variables
}
