
import java.util.Random;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lilil
 */
public class Sic_bo extends javax.swing.JFrame {

    /**
     * Creates new form Sic_bo
     */
    public Sic_bo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagemdado1 = new javax.swing.JLabel();
        imagemdado2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Sic bo");

        imagemdado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dado 6.png"))); // NOI18N

        imagemdado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dado 6.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Jogar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(imagemdado1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(imagemdado2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemdado1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemdado2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Random rnd = new Random();
        int dado1 = 0;
        dado1 = ((int)(rnd.nextDouble()*6));
        int dado2 = 0;
        dado2 = ((int)(rnd.nextDouble()*6));
        
        if (dado1==0){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 1.png")));
        }
        else if (dado1==1){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 2.png")));
        }
        else if (dado1==2){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 3.png")));
        }
        else if (dado1==3){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 4.png")));
        }
        else if (dado1==4){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 5.png")));
        }
        else if (dado1==5){
            imagemdado1.setIcon(new ImageIcon(getClass().getResource("dado 6.png")));
        }
        if (dado2==0){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 1.png")));
        }
        else if (dado2==1){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 2.png")));
        }
        else if (dado2==2){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 3.png")));
        }
        else if (dado2==3){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 4.png")));
        }
        else if (dado2==4){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 5.png")));
        }
        else if (dado2==5){
            imagemdado2.setIcon(new ImageIcon(getClass().getResource("dado 6.png")));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javimagemdado1orial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sic_bo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 imagemdado1} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sic_bo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sic_bo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sic_bo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sic_bo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagemdado1;
    private javax.swing.JLabel imagemdado2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
